### ISSUE TITLE
How to send value tag to build URL (permalink)

### ISSUE THREAD

**Issue by ctrl-b** [jeffkole/jekyll-page-collections#2]
I'm trying to find the way to send my tag value 

``` liquid
lang: fr
```

of my document collection so in that way I can get a URL for a specified language

``` liquid
/fr/{collection_name}/title/
```

Any ideas?

thank you !

**Comment by jeffkole** [comment]
The easiest thing to do may be to prefix the use of `page_url` with the tag value.  Something along the lines of

```
[Name of link](/{{ lang }}{% page_url collection_name page_name %})
```
